sudo: required

language: node_js

node_js:
  - '9'
  - '8'

cache:
  directories:
    - "node_modules"

script:
  - cd ${TRAVIS_BUILD_DIR}/modules/nodejs-agent && npm install && npm run check
  - cd ${TRAVIS_BUILD_DIR}/modules/skywalking-egg-require && npm install && npm run check
