name: Test

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  Test:
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use NodeJS 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Test
        run: cd modules/nodejs-agent && npm i && npm run test
